# Generated by Django 5.0.3 on 2024-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.BigIntegerField(),
        ),
    ]
