# Generated by Django 5.0.3 on 2024-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_system', '0004_remove_attendancerecord_classf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classregister',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
